### ISSUE TITLE
blocker: yum-utils package has been 'deprecated' on fedora-latest

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#186]
What are the steps to reproduce this issue?
-------------------------------------------
1. create PR
2. look at travis CI build for 'gnupg-git-fedora-latest'
 For example, the second to last build here: 
   https://travis-ci.org/sobolevn/git-secret/builds/389721094
(note also is likely the last issue to keep this build from passing)

What happens?
-------------
Travis Ci build fails and reports:
````
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.
````

What were you expecting to happen?
----------------------------------
successful build

Any logs, error output, etc?
----------------------------
The issue is related to 
https://github.com/sobolevn/git-secret/blob/master/.ci/integration/gnupg-git/default.yml#L50
where it reads:

````
    - name: Install gnupg build dependencies for RedHat based distros
      command: bash -lc "yum --assumeyes install yum-utils && yum-builddep --assumeyes gnupg2"
      when:
        - ansible_os_family == "RedHat"
````

You can see the error output it generates here:
https://travis-ci.org/sobolevn/git-secret/jobs/389668874

Any other comments?
-------------------
 yum-utils has been deprecated we get a non-zero exit code.

the yum-utils package is used for the yum-builddep tool
