### ISSUE TITLE
How to add git secret hide comand to pre-commit-config.yaml

### ISSUE THREAD

**Issue by bilalbayasut** [sobolevn/git-secret#489]
What are the steps to reproduce this issue?
-------------------------------------------
1. adding git secret hide command instide pre-commit-config.yaml
```
- repo: https://github.com/sobolevn/git-secret
    rev: v0.2.6
    hooks:
      - id: git-secret-hide
        name: encrypt secrets
        files: pre-commit.sh
        types: ["file", "executable","bash"]
```

What happens?
-------------
cannot add pre-commit

What were you expecting to happen?
----------------------------------
pre-commit for `git secret hide` command is added and executed every pre - commit

What versions of software are you using?
----------------------------------------
**Operating system:** ubuntu bionics

**Comment by joshrabinowitz** [comment]
Hello @bilalbayasut , thank you for this issue report.

Are you using pre-commit  from <https://pre-commit.com/> here? 

Can you provide all the steps to reproduce your issue, and also paste in any error messages you get? 

It may also be useful to run `git-secret hide` with the `-v` option, which will have git-secret show verbose output while it runs, which may help us understand this issue.

**Comment by bilalbayasut** [comment]
@joshrabinowitz yes you are right, I used pre-commit from there. to reproduce I just add code below to pre-commit-config.yaml :
```
- repo: https://github.com/sobolevn/git-secret
    rev: v0.2.6
    hooks:
      - id: git-secret-hide
        name: encrypt secrets
        files: pre-commit.sh
        types: ["file", "executable","bash"]
```
here is the error
```
An error has occurred: InvalidManifestError: 
=====> /home/bilal/.cache/pre-commit/repotfhzsyr1/.pre-commit-hooks.yaml does not exist
Check the log at /home/bilal/.cache/pre-commit/pre-commit.log
```
