### ISSUE TITLE
Doesn't work with pgp key without a password

### ISSUE THREAD

**Issue by gudata** [sobolevn/git-secret#520]
Create a pgp key without a password

What happens?
-------------
It can't reveal the secret
```
git secret reveal
gpg: decryption failed: No secret key
git-secret: abort: problem decrypting file with gpg: exit code 2: //projecti/.env.development
```

What were you expecting to happen?
----------------------------------
To work without a password.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Linux T540p 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
/usr/bin

**`git-secret` version:** (`git secret --version`) …
0.2.5

**`git` version:** (`git --version`) …
2.20.1
**Shell type and version:** (`$SHELL --version`) …
NU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.12
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/guda/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment]
@gudata can you please retry with the current master branch (preferably) or with git-secret 0.2.6, and using `git-secret`'s -v option?

I've done plenty of testing with pgp keys without passwords, and I have not encountered this issue - it looks more like you have the public key but not the private key for your gnupg keypair.

If you are still encountering this issue after making sure you have both the public and private halfs of the keypair, please write back with more details on the set up steps so I can try to replicate the issue.

**Comment by gudata** [comment]
You are absolutely right. When I verified that the private key is in place everything works.
here is what I did in order to reveal the secrets in a docker/drone container

```
pipeline:
  pgp-reveal:
    image: python:3.7.4-buster
    commands:
      - apt-get update && apt-get install -y -q gawk
      - git clone https://github.com/sobolevn/git-secret.git /tmp/git-secret
      - cd /tmp/git-secret && make build
      - PREFIX="/usr/local" make install
      - cd /drone/src

      - echo "Importing the key"
      - ls -la /opt/drone
      - gpg --batch --import /opt/drone/drone-private-key.asc
      - gpg --list-secret-keys
      - ls -la
      - git secret --version
      - git secret reveal -v -f
      - cat .env.development
    volumes:
      - /home/guda/projects/drone:/opt/drone
```

Thank you!
