### ISSUE TITLE
Getting "partial length invalid for packet type 20" error in github actions 

### ISSUE THREAD

**Issue by panslava** [sobolevn/git-secret#739]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create new key locally
2. Export secret file, paste it contents to github secrets
3. Add the next action

```
name: test-action
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install git-secret
        env:
          SECRETS_VERBOSE: 1
          PREFIX: "/usr/local"
        run: |
          git clone https://github.com/sobolevn/git-secret.git git-secret
          cd git-secret
          sudo make build
          sudo make install

      - name: Configure GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Reveal secrets
        env:
          SECRETS_VERBOSE: 1
        run: |
          git secret reveal
```

What happens?
-------------

On the "Reveal secrets step"  getting error:
```
gpg: [don't know]: partial length invalid for packet type 20
git-secret: abort: problem decrypting file with gpg
```

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) 
locally: 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16\~1/RELEASE_X86_64 x86_64
gh-actions: Linux fv-az139-698 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`)
locally: /usr/local/bin/git-secret
gh actions: /usr/bin/git-secret

**`git-secret` version:** (`git secret --version`)
locally: 0.4.0
gh actions: 0.5.0-alpha1

**`git` version:** (`git --version`)
locally: 2.29.2
gh actions: 2.34.1

**Shell type and version:** (`$SHELL --version`)
locally: zsh 5.7.1 (x86_64-apple-darwin19.0)
gh actions: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**`gpg` version:** (`gpg --version`)
locally: gpg (GnuPG) 2.3.2 libgcrypt 1.9.4
gh actions: gpg (GnuPG) 2.2.19 libgcrypt 1.8.5
